runtime system.vim

set nocompatible

if has('autocmd')
  let g:maplocalleader = ','
  filetype plugin indent on
endif

scriptencoding utf-8

if has('multi_byte') && !exists('$LANG')
  set encoding=utf-8
endif

if isdirectory(expand("$HOME/.vim"))
  let $VIMDIR=expand("$HOME/.vim")
  execute 'set runtimepath^='. "$VIMDIR"
elseif &runtimepath !=# ''
  let $VIMDIR = split(&runtimepath, ',')[0]
endif

" Bootstrap native packages: clone missing plugins on startup
let s:plugins = [
      \ ['pack/lsp/start/async.vim', 'https://github.com/prabirshrestha/async.vim.git'],
      \ ['pack/lsp/start/vim-lsp', 'https://github.com/prabirshrestha/vim-lsp.git'],
      \ ['pack/plugins/start/vim-go', 'https://github.com/fatih/vim-go.git'],
      \ ['pack/plugins/start/vim-terraform', 'https://github.com/hashivim/vim-terraform.git'],
      \ ['pack/plugins/start/rust.vim', 'https://github.com/rust-lang/rust.vim'],
      \ ]

for [s:path, s:url] in s:plugins
  let s:fullpath = $VIMDIR . '/' . s:path
  if !isdirectory(s:fullpath)
    echom 'Installing ' . s:path . '...'
    call mkdir(fnamemodify(s:fullpath, ':h'), 'p')
    call system('git clone --depth 1 ' . shellescape(s:url) . ' ' . shellescape(s:fullpath))
    if v:shell_error
      echoerr 'Failed to clone ' . s:url
    endif
  endif
endfor
unlet! s:path s:url s:fullpath

set t_Co=256
set background=dark
syntax on
colorscheme hybrid

" disable modelines due to arbitrary code execution vulnerabilities
" (CVE-2019-12735)
set modelines=0
set nomodeline

" appearance
set wildmenu

" Script-generated patterns to exclude when offering completions
set wildignore=*~,*.7z,.DS_Store,.git,.hg,.svn,*.a,*.avi,*.bin,*.bmp,*.bz2
      \,*.class,*.db,*.dbm,*.djvu,*.dll,*.docx,*.exe,*.flac,*.gif,*.gpg
      \,*.gz,*.ico,*.iso,*.jar,*.jpeg,*.jpg,*.m4a,*.o,*.ogg,*.ogv,*.opus
      \,*.orig,*.pdf,*.png,*.ppt,*.pyc,*.rar,*.rm,*.sqlite,*.so,*.swf
      \,*.swp,*.tar,*.tga,*.ttf,*.wav,*.webm,*.xls,*.xlsx,*.xz,*.zip

set wildignore+=*node_modules/**

" command history to keep
set history=10000

" hide startup message when opening Vim without a filename
set shortmess+=I

set laststatus=2

" show lines of context around the cursor
set scrolloff=5

" show matching braces
set showmatch

set title

" disable visual bell
set visualbell t_vb=

" behaviour

set timeoutlen=500

" chdir to the buffer in use
set autochdir

set mouse=v

set linebreak
" save on buffer switch
set autowrite

set spelllang=en_us
set dictionary^=/usr/share/dict/words
set spellcapcheck=

" line break when char >80
set textwidth=80

" copy and paste
vmap <C-c> "+yi
vmap <C-x> "+c
vmap <C-v> c<ESC>"+p
imap <C-v> <ESC>"+pa
noremap <Leader>y "*y
set clipboard=unnamedplus

" This Vim build lacks +clipboard, so 'clipboard' and the +/* registers
" cannot reach X11 on their own. Mirror every yank so other programs
" (browser, tmux) can paste it. Inside tmux, load-buffer -w hands the
" text to tmux, which forwards it to the terminal via OSC 52, keeping
" Alacritty the sole CLIPBOARD owner; a raw xclip here grabbed the
" selection on every yank and raced tmux's own OSC 52 stores, logging
" "Unable to store text in clipboard" in Alacritty and leaving an
" orphaned xclip process behind.
if !has('clipboard')
  function! s:YankToClipboard() abort
    if v:event.operator !=# 'y'
      return
    endif
    let l:text = join(v:event.regcontents, "\n")
    if v:event.regtype ==# 'V'
      let l:text .= "\n"
    endif
    if exists('$TMUX')
      call system('tmux load-buffer -w -', l:text)
    elseif executable('xclip') && exists('$DISPLAY')
      call system('xclip -selection clipboard', l:text)
    endif
  endfunction

  augroup clipboard_mirror
    autocmd!
    autocmd TextYankPost * call s:YankToClipboard()
  augroup END
endif

" Automatically enable paste mode when pasting
set pastetoggle=<F11>

set complete=.,w,b,u,t

set completeopt=longest,menuone

set backspace=indent,eol,start

set formatoptions+=n
set formatoptions+=l
set formatoptions-=t
set breakat=\ \\t\\=\\-\\_\\[\\{\\}\\|\\,\\.\\;\\:\'\\\"\\)\\]\\s\\$
set listchars=eol:$,tab:>-,trail:-,nbsp:+

if has('unix')
  set backup
  if !has('patch-8.1.1519')
    set backupskip&
  endif
  let s:backupdir=$HOME.'/.vim/backup/'
  set backupskip^=/dev/shm/*,/usr/tmp/*,/var/tmp/*,/tmp/*,$TMPDIR/*,$TMP/*,$TEMP/*
  if !isdirectory(s:backupdir)
    call mkdir(s:backupdir, 'p', 0700)
  endif
  execute 'set backupdir^='.s:backupdir
endif

" disable swap files
set noswapfile
" folding
set foldignore=
" re-indent from previous line
set autoindent
" uses spaces instead of tabs
set expandtab
" indent using four spaces when using indent operation
set shiftwidth=2
" indent intelligently but use 'tabstop' everywhere else
set smarttab
" spaces to show for a literal tab when 'list' is unset
set tabstop=2

set statusline+=%#LineNr#
" Display fullpath to file in the buffer
set statusline+=\ %F
" Denote modified, unsaved buffer with a plus (+) sign
set statusline+=%m
" Right-align statusline components below
set statusline+=%=
set statusline+=%#CursorColumn#
" Filetype
set statusline+=\ %y
" Show current position in buffer (percent)
set statusline+=\ %p%%
" line_nr:col_nr
set statusline+=\ %l:%c

" Apply 'softtabstop' on tab-press in insert mode using the same number of
" spaces as 'shiftwidth'
set softtabstop=2

au BufNewFile,BufRead *.txt setlocal noet tw=69 ts=4 sw=4
au BufNewFile,BufRead *.md,*.markdown,README setlocal spell noet ts=4 sw=4
au BufNewFile,BufRead *.json setlocal expandtab ts=4 sw=4
au BufNewFile,BufRead *.tex setlocal filetype=tex
au BufNewFile,BufRead muttrc,neomuttrc setlocal filetype=muttrc

autocmd FileType fstab,systemd setlocal noexpandtab
autocmd FileType gitcommit setlocal spell

autocmd FileType python setlocal expandtab shiftwidth=4 softtabstop=4 noautochdir
" Plan 9 kernel style
autocmd FileType c setlocal noexpandtab shiftwidth=2 softtabstop=2 tabstop=2
autocmd FileType sh setlocal expandtab shiftwidth=2 tabstop=2

" search

" search result highlighting
set hlsearch

" case-insensitive search
set ignorecase
set smartcase

" search incrementally
set incsearch

" don't redraw screen during execution of macros and scripts
set lazyredraw

" ms delay before showing match
set mat=2

" Maximum number of columns per line that syntax highlighting will match
set synmaxcol=512

" paths where tags may be located
set tags=./tags,tags;$HOME

" mappings
let mapleader = ","

" faster way to exit insert mode
inoremap jj <Esc>

nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;

" Maps the spacebar key in normal mode to clear the search highlighting.
nnoremap <silent> <Space> :nohlsearch<CR>

" Toggle spell checking
nnoremap <Leader>s
      \ :<C-U>set spell! spell?<CR>

" seamless vim/tmux pane navigation
function! s:TmuxNavigate(dir)
  let nr = winnr()
  execute 'wincmd ' . a:dir
  if nr == winnr()
    let tmux_dir = tr(a:dir, 'hjkl', 'LDUR')
    silent call system('tmux select-pane -' . tmux_dir)
  endif
endfunction

nnoremap <silent> <C-H> :call <SID>TmuxNavigate('h')<CR>
nnoremap <silent> <C-J> :call <SID>TmuxNavigate('j')<CR>
nnoremap <silent> <C-K> :call <SID>TmuxNavigate('k')<CR>
nnoremap <silent> <C-L> :call <SID>TmuxNavigate('l')<CR>

" disable arrow keys when in normal/visual mode
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>

" switch to the current buffer's alternative buffer
nnoremap <Backspace> <C-^>

" write to buffer as superuser
cmap w!! w !sudo tee > /dev/null %

" Strip trailing whitespace
nnoremap <Leader>ws
      \:%s/\s\+$//<cr>:let @/=''<CR>

"" Leader,l toggles showing tab, end-of-line, and trailing white space
noremap <Leader>l
      \ :<C-U>set list! list?<CR>

" undo peristence
if has('persistent_undo')
  let s:undodir = expand($VIMDIR.'/cache/undo')
  if !isdirectory(s:undodir)
    call mkdir(s:undodir, 'p')
  endif
  let &undodir = s:undodir
  set undofile

  " delete undo history files after 30 days
  let s:undos = split(globpath(&undodir, '*'), "\n")
  call filter(s:undos, 'getftime(v:val) < localtime() - (60 * 60 * 24 * 30)')
  call map(s:undos, 'delete(v:val)')
endif

augroup vimrcEx
  au!
  autocmd FileType text setlocal textwidth=79

  " When editing a file, always jump to the last known cursor position,
  " except when:
  " - the cursor position be invalid or inside an event handler
  " - mark is the first line
  autocmd BufReadPost *
        \ if line("'\"") > 1 && line("'\"") <= line("$") |
        \	exe "normal! g`\"" |
        \ endif
augroup END

" use vim session as manpager
runtime! ftplugin/man.vim

nnoremap <Leader>1 :Lexplore<CR>
let g:netrw_banner = 0

" vim-lsp configuration
if executable('pylsp')
  au User lsp_setup call lsp#register_server({
        \ 'name': 'pylsp',
        \ 'cmd': {server_info->['pylsp']},
        \ 'allowlist': ['python'],
        \ })
endif

" vim-go ships its own gopls client, but it does not serve vim-lsp's
" <plug>(lsp-*) mappings, so gr reported no server for go files. Passing
" -remote=auto here matches vim-go's default (autoload/go/config.vim), which
" makes both clients share one gopls daemon instead of starting a second.
"
" gopls is located explicitly rather than trusting PATH: .path expands
" ${GOPATH} before .env exports it, so $GOPATH/bin never enters PATH and a
" bare executable('gopls') test fails.
let s:gopls = 'gopls'
if !executable(s:gopls)
  let s:gopls = expand('$GOPATH/bin/gopls')
endif

if executable(s:gopls)
  " Anchor the workspace on go.mod so references and symbol search span the
  " whole module rather than only the current file's directory.
  au User lsp_setup call lsp#register_server({
        \ 'name': 'gopls',
        \ 'cmd': {server_info->[s:gopls, '-remote=auto']},
        \ 'allowlist': ['go', 'gomod'],
        \ 'root_uri': {server_info->lsp#utils#path_to_uri(
        \     lsp#utils#find_nearest_parent_file_directory(
        \       lsp#utils#get_buffer_path(), 'go.mod'))},
        \ })
endif

function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  setlocal signcolumn=yes
  if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
  nmap <buffer> gd <plug>(lsp-definition)
  nmap <buffer> gs <plug>(lsp-document-symbol-search)
  nmap <buffer> gS <plug>(lsp-workspace-symbol-search)
  nmap <buffer> gr <plug>(lsp-references)
  nmap <buffer> gi <plug>(lsp-implementation)
  nmap <buffer> gt <plug>(lsp-type-definition)
  nmap <buffer> <leader>rn <plug>(lsp-rename)
  nmap <buffer> [g <plug>(lsp-previous-diagnostic)
  nmap <buffer> ]g <plug>(lsp-next-diagnostic)
  nmap <buffer> K <plug>(lsp-hover)
  nnoremap <buffer> <expr><c-f> lsp#scroll(+4)
  nnoremap <buffer> <expr><c-d> lsp#scroll(-4)

  let g:lsp_format_sync_timeout = 1000
  autocmd! BufWritePre *.py call execute('LspDocumentFormatSync')
endfunction

augroup lsp_install
  au!
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

let g:lsp_diagnostics_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_diagnostics_float_cursor = 1
let g:lsp_diagnostics_signs_enabled = 1
let g:lsp_diagnostics_virtual_text_enabled = 0
let g:lsp_document_highlight_enabled = 0
